name: Publish Podspec

on:
  workflow_dispatch:
    branches:
    - master

jobs:
  publish-pod-spec:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish pod spec
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: pod trunk push DLParser.podspec
