name: Swift

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: Podfile.lock
      - name: Install dependencies
        run: pod install
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Run unit tests
        run: >
          xcodebuild clean test
          -workspace 'DLParser.xcworkspace'
          -scheme 'DLParser'
          -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2'
